---
- name: Install autossh
  apt:
    name: autossh
    state: present

- name: Generate SSH tunnel service files
  template:
    src: templates/sshtunnel.service.j2
    dest: /etc/systemd/system/ssh-tunnel-{{ item.name }}.service
    mode: '0644'
  loop: "{{ tunnels }}"

- name: Reload systemctl daemon
  command: systemctl daemon-reload

- name: Enable SSH tunnel services
  systemd:
    name: "ssh-tunnel-{{ item.name }}"
    enabled: yes
    state: started
  loop: "{{ tunnels }}"
